name: Emscripten Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  emscripten-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache emsdk
      uses: actions/cache@v4
      with:
        path: |
          ~/.emsdk
          ~/.emscripten_cache
        key: ${{ runner.os }}-emsdk-cache

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev


    - name: Install Emscripten SDK
      run: |
        git clone https://github.com/emscripten-core/emsdk.git ~/.emsdk
        cd ~/.emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh

    - name: Configure and Build with Emscripten
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        emcc . -o output.html

    - name: Upload WASM build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-build
        path: |
          build/*.html
          build/*.wasm
          build/*.js
